### ISSUE TITLE
Translate subcategory names and other main texts

### ISSUE THREAD

**Issue by per1234** [arduino/reference-pl#3]
There is some text to translate that is not in this repository's content. Please translate the following list and add the translation as a reply here:

- Arduino Reference
- The Arduino programming language Reference, organized into Functions, Variable and Constant, and Structure keywords.
- functions
- For controlling the Arduino board and performing computations.
- Digital I/O
- Analog I/O
- Zero, Due & MKR Family
- Advanced I/O
- Time
- Math
- Trigonometry
- Characters
- Random Numbers
- Bits and Bytes
- External Interrupts
- Interrupts
- Communication
- Serial
- Stream
- USB
- Keyboard
- Mouse
- variables
- Arduino data types and constants.
- Constants
- Conversion
- Data Types
- Variable Scope & Qualifiers
- Utilities
- structure
- The elements of Arduino (C++) code.
- Sketch
- Control Structure
- Further Syntax
- Arithmetic Operators
- Comparison Operators
- Boolean Operators
- Pointer Access Operators
- Bitwise Operators
- Compound Operators

**Comment by tomb0x** [comment]
- Omówienie Arduino
- Omówienie języka programowania Arduino, podzielone jest na słowa kluczowe Funkcji, Zmiennych i Stałych oraz Struktury.
- funkcje
- Do sterowania płytą Arduino i wykonywania obliczeń.
- Cyfrowe We/Wy
- Analogowe We/Wy
- Rodzina Zero, Due i MKR
- Zaawansowane We/Wy
- Czas
- Matematyka
- Trygonometria
- Znaki
- Liczby losowe
- Bity i Bajty
- Przerwania zewnętrzne
- Przerwania
- Komunikacja
- Szeregowe
- Strumień
- USB (uniwersalna magistrala szeregowa)
- Klawiatura
- Mysz
- zmienne
- typy danych i stałe Arduino
- Stałe
- Konwersja
- Typy danych
- Zasięg zmiennej i kwalifikatory
- Narzędzia
- struktura
- Elementy kodu Arduino (C++).
- Szkic
- Struktura sterowania
- Składnia dodatkowa
- Operatory arytmetyczne
- Operatory porównania
- Operatory logiczne
- Operatory dostępu do wskaźnika
- Operatory bitowe
- Operatory złożone

**Comment by tomb0x** [comment]
language polishing:
1- (Language Reference) from 'Omówienie Arduino' and/or 'Studium Języka' to 'Dokumentacja języka'...
2- (Control Structure) 'Struktura sterowania' -> 'Instrukcje sterujące'
3- (Further Syntax) 'Składnia dodatkowa' (ugly...) -> just 'Składnia'
